# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Private CI trigger.  Used to run tooling that can't currently be shared
# publicly.
#
variables:
- template: vars.yml

trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - "*"
pr:
  branches:
    include:
    - '*'

jobs:
- job: lint_dv
  displayName: Run quality checks (Lint and DV)
  pool: test
  steps:
  - bash: |
      ci/install-build-deps.sh
    displayName: Install build dependencies

  - bash: |
      echo $PATH
      python3 --version
      echo -n "fusesoc "
      fusesoc --version
      verilator --version
      riscv32-unknown-elf-gcc --version
      verible-verilog-lint --version
    displayName: Display environment
