# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# GitHub Action to run Verible linting on pull requests and add review comments.
#
# See https://github.com/chipsalliance/verible-linter-action.

name: pr-lint-review

# Triggers when there is any activity on a pull request, e.g. opened, updated.
#
# The action runs in the context of the _base_ of the pull request, but later we
# checkout the repository at the pull request's HEAD to run linting.
on:
  pull_request_target:

jobs:
  verible-lint:
    runs-on: ubuntu-latest
    # Grant write permissions only for setting checks and adding review comments
    # to pull requests.
    permissions:
      checks: write
      contents: read
      pull-requests: write
    env:
      verible_config: 'vendor/lowrisc_ip/lint/tools/veriblelint/lowrisc-styleguide.rules.verible_lint'
    steps:
      - uses: actions/checkout@v3
        with:
          # Because `pull_request_target` runs at the PR's base, we need to
          # checkout the head of the PR before running the lint.
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Display Verible config
        run: |
          echo "::group::Verible config"
          cat "$verible_config"
          echo "::endgroup::"
      - name: Run Verible linter action
        uses: chipsalliance/verible-linter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          suggest_fixes: 'false'
          config_file: ${{ env.verible_config }}
