# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
name: yosys-synthesis

on:
  push:
      branches:
        - master
  pull_request:

jobs:
    yosys-uhdm-synthesis:
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9
    steps:
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev git python3-pip
        update-alternatives --install /usr/bin/python python /usr/bin/python3 1
        update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: robinraju/release-downloader@v1.3
      with:
        repository: "antmicro/yosys-uhdm-plugin-integration"
        fileName: "yosys-uhdm-integration-*"
        latest: true
        tarBall: true

    - name: Extract yosys and UHDM plugin
      steps:
          tar -xzf yosys-uhdm-integration-*.tar.gz
          echo "$GITHUB_WORKSPACE/image" >> $GITHUB_PATH


    - name: Get memory file for Ibex
      steps:
          # TODO: Build it from source
          wget https://raw.githubusercontent.com/antmicro/yosys-uhdm-plugin-integration/master/uhdm-tests/ibex/led.vmem

    - name: Build & Test
      run: |
          pip install -r python-requirements.txt
          fusesoc --cores-root=. run --build --tool=yosys --target=synth lowrisc:ibex:top_artya7_surelog --SRAMInitFile=$GITHUB_WORKSPACE/led.vmem

    - uses: actions/upload-artifact@v2
      with:
        name: lowrisc_ibex_top_artya7_surelog_0.1.edif
        path: UHDM-integration-tests/build/lowrisc_ibex_top_artya7_surelog_0.1/synth-yosys/lowrisc_ibex_top_artya7_surelog_0.1.edif

